# Generated by Django 4.2.4 on 2023-08-02 22:32

import GestionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(validators=[GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50, validators=[GestionApp.models.caracteres_especiales_validator, GestionApp.models.sin_arrobas_validator, GestionApp.models.sin_numeros_validator, GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[GestionApp.models.precio_no_blanco_validator, GestionApp.models.precio_positivo_validator]),
        ),
        migrations.AlterField(
            model_name='docente',
            name='documento',
            field=models.CharField(max_length=20, validators=[GestionApp.models.caracteres_especiales_validator, GestionApp.models.sin_arrobas_validator, GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=50, validators=[GestionApp.models.caracteres_especiales_validator, GestionApp.models.sin_arrobas_validator, GestionApp.models.sin_numeros_validator, GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
    ]
