# Generated by Django 4.2.4 on 2023-08-02 22:43

import GestionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0002_alter_curso_descripcion_alter_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=50, validators=[GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
    ]
