# Generated by Django 4.2.4 on 2023-08-03 01:04

import GestionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0003_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='documento',
            field=models.CharField(max_length=20, unique=True, validators=[GestionApp.models.caracteres_especiales_validator, GestionApp.models.sin_arrobas_validator, GestionApp.models.sin_palabras_prohibidas_validator, GestionApp.models.sin_etiquetas_html_validator]),
        ),
    ]
